import { db } from "./db";
import { cfopCodes, cstCodes } from "@shared/schema";

export async function seedFiscalData() {
  try {
    const cfopData = [
      // ============= ENTRADA - INTERNA (1000-1999) =============
      {
        code: "1102",
        description: "Compra para revenda",
        type: "entrada",
        operationType: "compra",
        scope: "interna",
      },
      {
        code: "1201",
        description: "Devolução de venda",
        type: "entrada",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "1120",
        description: "Compra de matéria prima ou produto intermediário",
        type: "entrada",
        operationType: "compra",
        scope: "interna",
      },
      {
        code: "1121",
        description: "Compra de material de embalagem",
        type: "entrada",
        operationType: "compra",
        scope: "interna",
      },
      {
        code: "1130",
        description:
          "Compra de matéria prima, produto intermediário ou material de embalagem para industrialização",
        type: "entrada",
        operationType: "compra",
        scope: "interna",
      },
      {
        code: "1150",
        description: "Compra para devolução",
        type: "entrada",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "1170",
        description: "Compra em devolução (retorno ao fornecedor)",
        type: "entrada",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "1200",
        description: "Devolução de compra",
        type: "entrada",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "1202",
        description: "Devolução de compra para revenda",
        type: "entrada",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "1220",
        description: "Devolução de compra de matéria prima",
        type: "entrada",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "1250",
        description: "Compra de energia elétrica",
        type: "entrada",
        operationType: "compra",
        scope: "interna",
      },
      {
        code: "1300",
        description: "Bonificação recebida",
        type: "entrada",
        operationType: "bonificação",
        scope: "interna",
      },
      {
        code: "1350",
        description: "Industrialização por encomenda",
        type: "entrada",
        operationType: "industrialização",
        scope: "interna",
      },
      {
        code: "1400",
        description: "Remessa para industrialização",
        type: "entrada",
        operationType: "remessa",
        scope: "interna",
      },
      {
        code: "1500",
        description: "Remessa para venda fora do estabelecimento",
        type: "entrada",
        operationType: "remessa",
        scope: "interna",
      },
      {
        code: "1600",
        description: "Entrada de bem para uso ou consumo",
        type: "entrada",
        operationType: "compra",
        scope: "interna",
      },
      {
        code: "1900",
        description: "Entrada de outras operações",
        type: "entrada",
        operationType: "outros",
        scope: "interna",
      },

      // ============= ENTRADA - INTERESTADUAL (2000-2999) =============
      {
        code: "2102",
        description: "Compra para revenda",
        type: "entrada",
        operationType: "compra",
        scope: "interestadual",
      },
      {
        code: "2120",
        description: "Compra de matéria prima ou produto intermediário",
        type: "entrada",
        operationType: "compra",
        scope: "interestadual",
      },
      {
        code: "2121",
        description: "Compra de material de embalagem",
        type: "entrada",
        operationType: "compra",
        scope: "interestadual",
      },
      {
        code: "2150",
        description: "Compra para devolução",
        type: "entrada",
        operationType: "devolução",
        scope: "interestadual",
      },
      {
        code: "2201",
        description: "Devolução de venda",
        type: "entrada",
        operationType: "devolução",
        scope: "interestadual",
      },
      {
        code: "2202",
        description: "Devolução de compra para revenda",
        type: "entrada",
        operationType: "devolução",
        scope: "interestadual",
      },
      {
        code: "2250",
        description: "Compra de energia elétrica",
        type: "entrada",
        operationType: "compra",
        scope: "interestadual",
      },
      {
        code: "2300",
        description: "Bonificação recebida",
        type: "entrada",
        operationType: "bonificação",
        scope: "interestadual",
      },
      {
        code: "2400",
        description: "Remessa para industrialização",
        type: "entrada",
        operationType: "remessa",
        scope: "interestadual",
      },
      {
        code: "2900",
        description: "Entrada de outras operações",
        type: "entrada",
        operationType: "outros",
        scope: "interestadual",
      },

      // ============= SAÍDA - INTERNA (5000-5999) =============
      {
        code: "5102",
        description: "Venda de mercadoria",
        type: "saida",
        operationType: "venda",
        scope: "interna",
      },
      {
        code: "5103",
        description: "Venda de mercadoria ao consumidor final",
        type: "saida",
        operationType: "venda",
        scope: "interna",
      },
      {
        code: "5104",
        description:
          "Venda de mercadoria cobrada pelo ICMS por substituição tributária",
        type: "saida",
        operationType: "venda",
        scope: "interna",
      },
      {
        code: "5120",
        description: "Venda de matéria prima ou produto intermediário",
        type: "saida",
        operationType: "venda",
        scope: "interna",
      },
      {
        code: "5121",
        description: "Venda de material de embalagem",
        type: "saida",
        operationType: "venda",
        scope: "interna",
      },
      {
        code: "5150",
        description: "Venda para devolução",
        type: "saida",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "5200",
        description: "Devolução de compra",
        type: "saida",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "5202",
        description: "Devolução de compra para revenda",
        type: "saida",
        operationType: "devolução",
        scope: "interna",
      },
      {
        code: "5250",
        description: "Venda de energia elétrica",
        type: "saida",
        operationType: "venda",
        scope: "interna",
      },
      {
        code: "5300",
        description: "Bonificação fornecida",
        type: "saida",
        operationType: "bonificação",
        scope: "interna",
      },
      {
        code: "5350",
        description: "Remessa para industrialização",
        type: "saida",
        operationType: "remessa",
        scope: "interna",
      },
      {
        code: "5360",
        description: "Retorno de industrialização",
        type: "saida",
        operationType: "industrialização",
        scope: "interna",
      },
      {
        code: "5400",
        description: "Remessa para venda fora do estabelecimento",
        type: "saida",
        operationType: "remessa",
        scope: "interna",
      },
      {
        code: "5500",
        description: "Saída de bem para uso ou consumo",
        type: "saida",
        operationType: "venda",
        scope: "interna",
      },
      {
        code: "5900",
        description: "Saída de outras operações",
        type: "saida",
        operationType: "outros",
        scope: "interna",
      },

      // ============= SAÍDA - INTERESTADUAL (6000-6999) =============
      {
        code: "6102",
        description: "Venda de mercadoria",
        type: "saida",
        operationType: "venda",
        scope: "interestadual",
      },
      {
        code: "6103",
        description: "Venda de mercadoria ao consumidor final",
        type: "saida",
        operationType: "venda",
        scope: "interestadual",
      },
      {
        code: "6104",
        description:
          "Venda de mercadoria cobrada pelo ICMS por substituição tributária",
        type: "saida",
        operationType: "venda",
        scope: "interestadual",
      },
      {
        code: "6120",
        description: "Venda de matéria prima ou produto intermediário",
        type: "saida",
        operationType: "venda",
        scope: "interestadual",
      },
      {
        code: "6121",
        description: "Venda de material de embalagem",
        type: "saida",
        operationType: "venda",
        scope: "interestadual",
      },
      {
        code: "6150",
        description: "Venda para devolução",
        type: "saida",
        operationType: "devolução",
        scope: "interestadual",
      },
      {
        code: "6200",
        description: "Devolução de compra",
        type: "saida",
        operationType: "devolução",
        scope: "interestadual",
      },
      {
        code: "6202",
        description: "Devolução de compra para revenda",
        type: "saida",
        operationType: "devolução",
        scope: "interestadual",
      },
      {
        code: "6250",
        description: "Venda de energia elétrica",
        type: "saida",
        operationType: "venda",
        scope: "interestadual",
      },
      {
        code: "6300",
        description: "Bonificação fornecida",
        type: "saida",
        operationType: "bonificação",
        scope: "interestadual",
      },
      {
        code: "6350",
        description: "Remessa para industrialização",
        type: "saida",
        operationType: "remessa",
        scope: "interestadual",
      },
      {
        code: "6400",
        description: "Remessa para venda fora do estabelecimento",
        type: "saida",
        operationType: "remessa",
        scope: "interestadual",
      },
      {
        code: "6900",
        description: "Saída de outras operações",
        type: "saida",
        operationType: "outros",
        scope: "interestadual",
      },

      // ============= SAÍDA - EXTERIOR (7000-7999) =============
      {
        code: "7102",
        description: "Venda de mercadoria para o exterior",
        type: "saida",
        operationType: "venda",
        scope: "exterior",
      },
      {
        code: "7350",
        description: "Remessa para industrialização para o exterior",
        type: "saida",
        operationType: "remessa",
        scope: "exterior",
      },
      {
        code: "7500",
        description: "Saída de bem para uso ou consumo (exterior)",
        type: "saida",
        operationType: "venda",
        scope: "exterior",
      },
      {
        code: "7900",
        description: "Saída de outras operações (exterior)",
        type: "saida",
        operationType: "outros",
        scope: "exterior",
      },
    ];

    const cstData = [
      {
        code: "101",
        description: "Tributada com crédito",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "102",
        description: "Tributada sem crédito",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "103",
        description: "Isenção",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "201",
        description: "Substituição tributária (sem ICMS próprio)",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "202",
        description:
          "Substituição tributária - com ICMS próprio (parte não retida)",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "203",
        description: "Substituição tributária - isento de ST",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "300",
        description: "Imune",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "400",
        description: "Não tributada",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "500",
        description: "Diferimento",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "900",
        description: "Outros",
        codeType: "CSOSN",
        taxType: "ICMS",
        regime: "Simples Nacional",
      },
      {
        code: "00",
        description: "Tributação normal",
        codeType: "CST",
        taxType: "ICMS",
        regime: "Lucro Real",
      },
      {
        code: "10",
        description: "Com substituição tributária",
        codeType: "CST",
        taxType: "ICMS",
        regime: "Lucro Real",
      },
    ];

    await db.insert(cfopCodes).values(cfopData).onConflictDoNothing();
    await db.insert(cstCodes).values(cstData).onConflictDoNothing();

    console.log("✓ Fiscal data seeded successfully");
  } catch (error) {
    console.error("Error seeding fiscal data:", error);
  }
}
